version: '3.8'

services:
  backend:
    build: backend
    environment:
      - REDIS_URL=redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - redis
      
  frontend:
    build: frontend
    ports:
      - "5173:5173"

  redis:
    image: redis
    ports:
      - "6379:6379"
